// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArr = "arr"

// Arr mapped from table <arr>
type Arr struct {
	F1 string `gorm:"column:f1" json:"f1"`
	F2 string `gorm:"column:f2" json:"f2"`
}

// TableName Arr's table name
func (*Arr) TableName() string {
	return TableNameArr
}
