// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArticle = "articles"

// Article mapped from table <articles>
type Article struct {
	ID            int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title         string `gorm:"column:title" json:"title"`
	Content       string `gorm:"column:content" json:"content"`
	ContentVector string `gorm:"column:content_vector" json:"content_vector"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
