// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCityCapital = "city_capital"

// CityCapital mapped from table <city_capital>
type CityCapital struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name  string `gorm:"column:name;not null" json:"name"`
	Num   int32  `gorm:"column:num" json:"num"`
	State bool   `gorm:"column:state;default:true" json:"state"`
}

// TableName CityCapital's table name
func (*CityCapital) TableName() string {
	return TableNameCityCapital
}
