// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEmployee = "employees"

// Employee mapped from table <employees>
type Employee struct {
	ID    int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name  string    `gorm:"column:name;not null" json:"name"`
	Email string    `gorm:"column:email;not null" json:"email"`
	Date  time.Time `gorm:"column:date" json:"date"`
	Core  float64   `gorm:"column:core;not null;comment:分数" json:"core"` // 分数
}

// TableName Employee's table name
func (*Employee) TableName() string {
	return TableNameEmployee
}
