// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameJsonbUser = "jsonb_users"

// JsonbUser mapped from table <jsonb_users>
type JsonbUser struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Info string `gorm:"column:info" json:"info"`
}

// TableName JsonbUser's table name
func (*JsonbUser) TableName() string {
	return TableNameJsonbUser
}
