// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMenu = "menus"

// Menu mapped from table <menus>
type Menu struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name     string `gorm:"column:name;not null" json:"name"`
	Link     string `gorm:"column:link" json:"link"`
	Sort     int32  `gorm:"column:sort" json:"sort"`
	ParentID int32  `gorm:"column:parent_id" json:"parent_id"`
	Xx       string `gorm:"column:xx" json:"xx"`
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
