// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "orders"

// Order mapped from table <orders>
type Order struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CustomerID int64     `gorm:"column:customer_id" json:"customer_id"`
	Product    string    `gorm:"column:product" json:"product"`
	Amount     float64   `gorm:"column:amount" json:"amount"`
	OrderDate  time.Time `gorm:"column:order_date" json:"order_date"`
	Status     string    `gorm:"column:status" json:"status"`
	IsOver     bool      `gorm:"column:is_over" json:"is_over"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
