// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSale = "sales"

// Sale mapped from table <sales>
type Sale struct {
	Item     string `gorm:"column:item" json:"item"`
	Year     string `gorm:"column:year" json:"year"`
	Quantity int32  `gorm:"column:quantity" json:"quantity"`
}

// TableName Sale's table name
func (*Sale) TableName() string {
	return TableNameSale
}
