// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSnowflakeSequence = "snowflake_sequence"

// SnowflakeSequence mapped from table <snowflake_sequence>
type SnowflakeSequence struct {
	MachineID  int64 `gorm:"column:machine_id;not null" json:"machine_id"`
	Sequence   int64 `gorm:"column:sequence;not null" json:"sequence"`
	LastMillis int64 `gorm:"column:last_millis;not null" json:"last_millis"`
}

// TableName SnowflakeSequence's table name
func (*SnowflakeSequence) TableName() string {
	return TableNameSnowflakeSequence
}
